### ISSUE TITLE
donald missing

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/HpoCaseAnnotator#114]
Creating temporary directory at /tmp/hca_app
Packaging classpath Hpo Case Annotator for Linux
cp: cannot stat 'hpo-case-annotator-app/target/hpo-case-annotator-app-2.0.0-RC1-SNAPSHOT.jar': No such file or directory
Error: Specified icon file [/home/peter/IdeaProjects/HpoCaseAnnotator/hpo-case-annotator-app/target/classes/img/donald-duck.png] does not exist
Removing the temporary directory /tmp/hca_app
Done!

**Comment by ielis** [comment]
Fixed to #116
