### ISSUE TITLE
Feature request: Bigger dropdown box for disease name

### ISSUE THREAD

**Issue by LCCarmody** [monarch-initiative/HpoCaseAnnotator#24]
NOT URGENT.

Having issues with long named diseases and choosing between the different types.

Example: I wanted SPONDYLOEPIMETAPHYSEAL DYSPLASIA WITH JOINT LAXITY, TYPE 1, WITH ORWITHOUT FRACTURES; SEMDJL1

But I was typing it in from the paper--so I didn't exactly know what it was called.  The first that came up was Type 2...and it was very difficult to search through the results to select what I wanted.

**Comment by ielis** [comment]
Resolved, will be available in release `1.0.11`
