### ISSUE TITLE
Text mining not working in release Hpo Case Annotator v1.0.11

### ISSUE THREAD

**Issue by LCCarmody** [monarch-initiative/HpoCaseAnnotator#43]
Text mining is not working at all in Hpo Case Annotator v1.0.11, but the HPO tree browser still does work.

**Comment by ielis** [comment]
This looks like an issue outside of the Hpo Case Annotator. More specifically, Scigraph service that is supposed to perform text-mining returns an empty response. Therefore no term is highlighted in the text.

We need to investigate more..

**Comment by ielis** [comment]
@LCCarmody - we finally fixed the bug. The fix, however, will be available only in the next release which I will make soon.

This new one will also include a small changes in location of data directory (the one where OBO and FASTA files exist). Starting now, the app will be able to use data from the previous versions.
