### ISSUE TITLE
Get accession # doesn't do anything except get accession

### ISSUE THREAD

**Issue by LCCarmody** [monarch-initiative/HpoCaseAnnotator#44]
Also in Hpo Case Annotator v1.0.11, when you hit the 'Get accession' button, you do accurately get the accession number(s). However, if you hit the accesssion number button, another window opens and it seems like you could add the accession number and variant and then hit 'ok' it should lead somewhere?  It doesn't.  Is it supposed to go to variantvalidator?

**Comment by pnrobinson** [comment]
this seems to be working now
