### ISSUE TITLE
FamilyInfo

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/HpoCaseAnnotator#48]
I am concerned that code such as this is fragile:
```
   case 10: 
```
Can we explore how to do this using named getters/setters? 
A lot of the code is now marked as deprecated as well.

**Comment by ielis** [comment]
@pnrobinson  could you please be more verbose? I don't understand what the issue is about.

**Comment by pnrobinson** [comment]
It seems that the code is using the numbers of the elements in the case statement. However, with the 0.4.0 version of phenopackets, the numbering was changed, or it could change in the future. It would be nice to use named getters/setters -- but perhaps I am misunderstanding something?

**Comment by ielis** [comment]
I am not aware that there is such a line in `HpoCaseAnnotator` code. Could you please provide a link here?

**Comment by pnrobinson** [comment]
my dumb, NEVERMIND https://www.youtube.com/watch?v=VrbybKWwb7c
