### ISSUE TITLE
Genome build/ Assembly could be an Enum

### ISSUE THREAD

**Issue by julesjacobsen** [monarch-initiative/HpoCaseAnnotator#5]
https://github.com/monarch-initiative/HpoCaseAnnotator/blob/41de1682f165405d0b16f6e67b1a21f7b1b6b2d7/hpo-case-annotator-core/src/main/proto/model.proto#L9

see 

https://github.com/phenopackets/phenopacket-schema/blob/4ce66acabfd3cc0f66e0a33bc5199bb80c4b2c87/src/main/proto/org/phenopackets/schema/v1/core/base.proto#L509-L521

if you want the patch version this won't be ideal, but could be included in a compound type e.g.

```proto
message GenomeAssemblyWithPatch {
 GenomeAssembly genome_assembly = 1;
 int32 patch = 2;
}
```

**Comment by ielis** [comment]
Let's close it.
