### ISSUE TITLE
phenopacket id missing

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/HpoCaseAnnotator#59]
I am progressing with the C++ validator. Now I think it is validating the entire RD phenopacket, and it seems that the only error is that there is no id for the phenopaclet (see below). Probably we can give the id PMID_12345_patient_B or something like that

#### Phenopacket at: ../Gebbia-1997-ZIC3-III-1.json ####

Phenopacket:
ID: III-1
Age: 7W
Sex: male
Arrhinencephaly [HP:0002139]
Single ventricle [HP:0001750]
Patent ductus arteriosus [HP:0001643]
Asplenia [HP:0001746]
Pulmonary artery hypoplasia [HP:0004971]
Complete atrioventricular canal defect [HP:0001674]
Transposition of the great arteries [HP:0001669]
Posteriorly placed anus [HP:0012890]
Ventricular septal defect [HP:0001629]
Abnormal ciliary motility [HP:0012262]
Pulmonary artery atresia [HP:0004935]
Abdominal situs inversus [HP:0003363]
Gene: ZIC3[ENTREZ:7547]
	GRCh37: X:136649818C>T[]
Disease: HETEROTAXY, VISCERAL, 1, X-LINKED; HTX1 [OMIM:306955]
Metadata:
Hpo Case Annotator : 1.0.13-SNAPSHOT(1970-01-01T00:00:00Z)
human phenotype ontology: hp(HP;http://purl.obolibrary.org/obo/hp.owl;2018-03-08;http://purl.obolibrary.org/obo/HP_)
Phenotype And Trait Ontology: pato(PATO;http://purl.obolibrary.org/obo/pato.owl;2018-03-28;http://purl.obolibrary.org/obo/PATO_)
Genotype Ontology: geno(GENO;http://purl.obolibrary.org/obo/geno.owl;19-03-2018;http://purl.obolibrary.org/obo/GENO_)
NCBI organismal classification: ncbitaxon(NCBITaxon;http://purl.obolibrary.org/obo/ncbitaxon.owl;2018-03-02;)
Evidence and Conclusion Ontology: eco(ECO;http://purl.obolibrary.org/obo/eco.owl;2018-11-10;http://purl.obolibrary.org/obo/ECO_)
Online Mendelian Inheritance in Man: omim(OMIM;https://www.omim.org;;)

#### We identified 1 Q/C issue ####
[ERROR] phenopacket id missing

**Comment by ielis** [comment]
Fixed
