### ISSUE TITLE
Malformed export of author name

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/HpoCaseAnnotator#61]
In the phenopacklet that gets exported from this publication:
1: Irfanullah, Umair M, Khan S, Ahmad W. Homozygous sequence variants in the NPR2
gene underlying Acromesomelic dysplasia Maroteaux type (AMDM) in consanguineous
families. Ann Hum Genet. 2015 Jul;79(4):238-44. doi: 10.1111/ahg.12116. Epub 2015
May 11. PubMed PMID: 25959430.

tghe export uses "author" instead of "Irfanullah"

```
"publication": {
    "authorList": "Irfanullah, Umair M, Khan S, Ahmad W",
    "title": "Homozygous sequence variants in the NPR2 gene underlying Acromesomelic dysplasia Maroteaux type (AMDM) in consanguineous families",
    "journal": "Ann Hum Genet",
    "year": "2015",
    "volume": "79(4)",
    "pages": "238-44",
    "pmid": "25959430"
  },
```

**Comment by ielis** [comment]
Fixed
