### ISSUE TITLE
Allow clinvar allele id instead of snippet

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/HpoCaseAnnotator#82]
We can annotate loads of clinvar variants >25kb, but it would be tedious to create snippets. Since this snippets are mainly intended to enable quality control, they are not really necessary if we have ClinVar ids. This is the kind of output a simple script to get variants >25bp looks like
```
PMID:19280650   11      112229366       485     TGTAAAGCACTGATAAAGTTTTTTTTTGTTGTTGTTGTTTTTTTTTTTGAGATGGA        T       .       .
       ALLELEID=15524;CLNDISDB=MONDO:M (....) RS=1555198165
```
The allele id corresponds to this page
https://www.ncbi.nlm.nih.gov/clinvar/variation/15524/

We should make the snippet non-required. There are at least two solutions
1. Add another window where we can enter an integer representing the AlleleId. In the class ``VariantSyntaxValidator`` only check the snippet if AlleleId is empty
2. Allow the user to enter ALLELEID:15524 in the Snippet field. Add another corresponding regex and if-clause near line 162 of ``VariantSyntaxValidator``
@ielis Thoughts?

**Comment by ielis** [comment]
Fixed by allowing to generate the snippet for _"mendelian"_ variants.
