### ISSUE TITLE
Unable to save data using a couple of fields

### ISSUE THREAD

**Issue by jagcsun** [monarch-initiative/HpoCaseAnnotator#86]
Hpo Case Annotator 1.0.14:
data entered in the fields Proband / family ID and Sex are **not** saved.

**Comment by ielis** [comment]
Hi @jagcsun ,
I looked into the code and I loaded/saved a couple of cases but I was not able to replicate the issue - the `Proband / family ID` & `Sex` attributes were saved into the output.

Do you see any unusual output in the terminal when working with the case file, where the attributes are not saved properly? Could you please share more details about how this happens?

**Comment by ielis** [comment]
Resolved.
